service:
  type: LoadBalancer
admin:
  existingSecret: grafana-secrets
  userKey: admin-user
  passwordKey: admin-password
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true
