config:
  server:
    http_listen_port: 9080
  positions:
    filename: /tmp/positions.yaml
  clients:
    - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
  scrape_configs:
    - job_name: system
      static_configs:
        - targets:
            - localhost
          labels:
            job: varlogs
            __path__: /var/log/*log
    - job_name: click-service
      static_configs:
        - targets:
            - localhost
          labels:
            job: click-service
            __path__: /var/log/click-service/*.log
