apiVersion: apps/v1
kind: Deployment
metadata:
  name: click-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: click-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: click-service
    spec:
      containers:
        - name: click-service
          image: ${image}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: 1000m
              memory: 1000Mi
          volumeMounts:
            - mountPath: /var/log/click-service
              name: log-volume
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: log-pvc
