apiVersion: apps/v1
kind: Deployment
metadata:
  name: click-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: click-service
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
  template:
    metadata:
      labels:
        app: click-service
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: click-service
          image: ${image}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /var/log/click-service
              name: log-volume
      volumes:
        - name: log-volume
          emptyDir: {}
