apiVersion: apps/v1
kind: Deployment
metadata:
  name: click-service
spec:
  selector:
    matchLabels:
      app: click-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  replicas: 1
  template:
    metadata:
      labels:
        app: click-service
    spec:
      containers:
        - name: click-service
          image: ${image}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 2000Mi
