spring:
  main:
    web-application-type: none
  data:
    redis:
      host: localhost
      port: 6380
  datasource:
    url: jdbc:mysql://localhost:3306/clickme?rewriteBatchedStatements=true
    username: clickme
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      name: ${job.name:NONE}

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}
