spring:
  main:
    web-application-type: none
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      name: ${job.name:NONE}

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}
