apiVersion: batch/v1
kind: CronJob
metadata:
  name: transfer-service
spec:
  schedule: 0 15 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: transfer-service
              image: ${image}
              args:
                - "--spring.batch.job.name=syncRedisToMysqlJob"
              env:
                - name: createAt
                  value: $(date -u +'%Y-%m-%dT%H:%M')
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: transfer-service
spec:
  schedule: 0 15 30 * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: transfer-service
              image: ${image}
              args:
                - "--spring.batch.job.name=profileImageUpdateJob"
              env:
                - name: createAt
                  value: $(date -u +'%Y-%m-%dT%H:%M')
          restartPolicy: OnFailure
