apiVersion: batch/v1
kind: CronJob
metadata:
  name: transfer-service1
spec:
  schedule: 0 15 * * *
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: transfer-service1
              image: ${image}:latest
              args:
                - "--spring.batch.job.name=syncRedisToMysqlJob createAt=$(date -u +'%Y-%m-%d')"
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: transfer-service2
spec:
  schedule: 30 15 * * *
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: transfer-service2
              image: ${image}:latest
              args:
                - "--spring.batch.job.name=profileImageUpdateJob createAt=$(date -u +'%Y-%m-%d')"
          restartPolicy: OnFailure
