name: CI-click-service

on:
  pull_request:
    branches: [ main ]
    paths:
      - click-service/**
      - .github/**

jobs:
  ci:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ./click-service

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission gradlew
        run: chmod +x ../gradlew

      - name: Test with Gradle
        run: ../gradlew test


