name: CI-transfer-service

on:
  pull_request:
    branches: [ main ]
    paths:
      - transfer-service/**
      - .github/**

jobs:
  ci:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ./transfer-service

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ github.job}}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-${{ github.job}}

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission gradlew
        run: chmod +x ../gradlew

      - name: Test with Gradle
        run: ../gradlew test


