name: cd for transfer-service
on:
  pull_request:
    branches: [ main ]
    paths:
      - transfer-service/**
      - .github/**

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
  REGION: ${{ secrets.REGION }}
  WORKSTATION_IMAGE: transfer-service
  VERSION: '1.0.1'
  IMAGE: ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.DOCKER_REPO }}/transfer-service
  REDIS_HOST: ${{secrets.REDIS_HOST}}
  REDIS_PORT: ${{secrets.REDIS_PORT}}
  DATASOURCE_URL: ${{secrets.DB_URL}}
  DATASOURCE_USERNAME: ${{secrets.DB_USERNAME}}
  DATASOURCE_PASSWORD: ${{secrets.DB_PASSWORD}}

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./transfer-service

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Set up google auth
        id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCE_SA_KEY }}

      - id: 'get-credentials'
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: autopilot-cluster-2
          location: ${{ env.REGION }}

      - name: Use gcloud CLI
        run: gcloud info

      - name: Docker auth
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Docker Build
        if: success()
        run: ../gradlew transfer-service:jib

      - name: Deploy
        run: |
          sed "s,\${image},${{ env.IMAGE }},g" resources.yaml > cronJob.yaml
          kubectl apply -f ./cronJob.yaml
          
